language: java
script: mvn clean verify
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: 766d1a9bc945aff484b3244381936661fb99f930
  file: /home/travis/build/luorigufeng/agile_tdd_guess_number/target/guess_number-0.1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    all_branches: true
