language: java
script: mvn clean verify
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: 8f05297027b4d0230e5f06163d20be5b6481b188
  file: /home/travis/build/luorigufeng/agile_tdd_guess_number/target/guess_number-0.1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    all_branches: true
